# Generated by Django 5.0 on 2024-12-15 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatisticas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20)),
                ('total_verificacoes', models.IntegerField(default=0)),
                ('total_inspecoes_invalidas', models.IntegerField(default=0)),
                ('verificacoes_matricula_invalida', models.IntegerField(default=0)),
                ('data_relatorio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatísticas',
                'db_table': 'Estatisticas',
            },
        ),
    ]
