# Generated by Django 5.0 on 2024-12-04 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsAPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_api', models.CharField(help_text='Nome ou URL da API utilizada.', max_length=255)),
                ('requisicao', models.TextField(help_text='Dados enviados para a pesquisa (parâmetros da requisição).')),
                ('resposta', models.TextField(help_text='Dados retornados pela API.')),
                ('data_hora', models.DateTimeField(auto_now_add=True, help_text='Data e hora da requisição.')),
                ('usuario', models.ForeignKey(help_text='Usuário que realizou a requisição.', on_delete=django.db.models.deletion.CASCADE, related_name='logs_api', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de API',
                'verbose_name_plural': 'Logs de API',
                'ordering': ['-data_hora'],
            },
        ),
    ]
