# Generated by Django 5.0 on 2024-12-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuscarInspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesquisar', models.CharField(help_text='Insira o código da inspeção a ser pesquisado', max_length=20, verbose_name='Código da Inspeção')),
            ],
        ),
        migrations.DeleteModel(
            name='Pesquisar',
        ),
    ]
