# Generated by Django 5.0 on 2024-12-01 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0003_pesquisar_delete_buscarinspecao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesquisar',
            options={'verbose_name': 'Pesquisa', 'verbose_name_plural': 'inspeções'},
        ),
        migrations.AddField(
            model_name='pesquisar',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
