# Generated by Django 5.0 on 2024-12-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0004_alter_pesquisar_options_pesquisar_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesquisar',
            options={'verbose_name': 'Pesquisa', 'verbose_name_plural': 'Inspeções'},
        ),
    ]
