# Generated by Django 5.0 on 2024-12-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nip',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
